package nl.bramkoene.minigameapi.Enums;

public enum BuildGameState {
    DEFAULT,
    CHOOSING_NAME,
    CHOOSING_MAX_PLAYERS,
    CHOOSING_TEAM_SIZE,
    CHOOSING_ALLOW_RESPAWN,
    SETTING_LOBBY_SPAWN_POINT,
    SETTING_GAME_SPAWN_POINTS,
    SETTING_KIT,
    PLACING_SIGN,
    SAVE
}
